proposed fix for failing tests in MasterRegistrationTest.
rjcausarano/rosjava_core pull request #3
Opened 2019-04-09 18:38 UTC by rjcausarano

Waits for all signals to be delivered before shutting down listeners in class DefaultPublisher.

2019-04-09 18:42 UTC, rjcausarano commented
Hey @jubeira, this might be what we were looking for. I went ahead and merged the previous PR that you reviewed and aproved so I don't understand why that commit is appearing as a change in this PR?

Also I'm pretty sure that there's a better way of handling the caught exception in the last commit. I'll make sure to fix that after your review and squash if necessary.

2019-04-09 20:45 UTC, rjcausarano commented
Alright this last commit does the following:

- log.error() in catch block
- shutdown latch uses passed timeout
- adds latch.countdown() to onMasterUnregistrationFailure()
- adds new testUnregisterPublisherFailure() test in class MasterRegistrationTest

2019-04-09 21:17 UTC, jubeira requested changes
Great job, thanks @rjcausarano!
I've left a couple of minor comments; please address them and squash everything into one commit before sending the PR upstream.

2019-04-09 21:17 UTC, jubeira commented on rosjava/src/main/java/org/ros/internal/node/topic/DefaultPublisher.java
> +    }
Please shrink the `try / catch` block only to the `await` call, and add a comment saying that in the normal workflow, `signalOnMasterUnregistration**` should finish execution before shutting down the listeners.

2019-04-09 21:17 UTC, jubeira commented on rosjava/src/main/java/org/ros/internal/node/topic/DefaultPublisher.java
> +    try{
nit: space after `try`

2019-04-09 21:17 UTC, jubeira commented on rosjava/src/test/java/org/ros/internal/node/MasterRegistrationTest.java
> +  }
:+1: Great!
It's a bit unfortunate that this test will take 10 secs (5 to shutdown the publisher and 5 to shutdown the node), but it's still a good idea to have it.

2019-04-09 21:17 UTC, jubeira commented on rosjava/src/main/java/org/ros/internal/node/topic/DefaultPublisher.java
> +    catch (InterruptedException e) {
nit: please put `catch` statement at the same line of the closing brace above: ` } catch (InterruptedException e) {`

2019-04-10 13:38 UTC, jubeira approved these changes
Awesome; LGTM! I think this can be sent upstream like this.

2019-04-10 13:42 UTC, merged